import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),hide=id=>$(id).classList.add('hidden'),show=id=>$(id).classList.remove('hidden');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9cc8ed);scene.fog=new THREE.Fog(0x9cc8ed,95,290);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,500);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.setSize(innerWidth,innerHeight);$('game').append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe8f4ff,0x6b8052,2.3));const sun=new THREE.DirectionalLight(0xffefd5,2.4);sun.position.set(-45,70,-70);scene.add(sun);
const mat=(c,m=0,r=.7)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r});
function box(parent,w,h,d,m,x=0,y=0,z=0){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);parent.add(o);return o}
function texture(base,green=false){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');g.fillStyle=base;g.fillRect(0,0,512,512);let seed=7267;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}for(let i=0;i<23000;i++){const v=40+rnd()*95|0;g.fillStyle=green?`rgba(${v*.45|0},${v|0},${v*.3|0},.28)`:`rgba(${v},${v},${v},.25)`;const s=.5+rnd()*2;g.fillRect(rnd()*512,rnd()*512,s,s)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());return t}
const roadTex=texture('#505252');roadTex.repeat.set(2.5,36);const grassTex=texture('#60844b',true);grassTex.repeat.set(50,50);
function plane(w,d,m,y,x=0,z=-110){const o=new THREE.Mesh(new THREE.PlaneGeometry(w,d),m);o.rotation.x=-Math.PI/2;o.position.set(x,y,z);scene.add(o);return o}
plane(600,600,new THREE.MeshStandardMaterial({map:grassTex}),-.15,0,-130);plane(17.2,460,new THREE.MeshStandardMaterial({map:roadTex,roughness:.98}),.01);
const white=mat(0xe7e6db),steel=mat(0x9da5aa,.7,.42),trunk=mat(0x655039),leaf=mat(0x477e43);const scenery=[];
for(const x of [-8.4,8.4]){box(scene,.2,.035,460,white,x,.055,-110);for(const y of [.45,.9])box(scene,.12,.14,460,steel,x>0?10.3:-10.3,y,-110)}
for(let z=-220;z<30;z+=13){for(const x of [-2.85,2.85])scenery.push({o:box(scene,.16,.03,5,white,x,.07,z),span:260});for(const x of [-10.3,10.3])scenery.push({o:box(scene,.14,1.1,.16,steel,x,.5,z),span:260})}
for(let i=0;i<33;i++)for(const side of [-1,1]){const t=new THREE.Group();const x=side*(16+(i%4)*2);t.position.set(x,0,-i*12-side*3);box(t,.4,2.6,.4,trunk,0,1.3,0);for(let j=0;j<3;j++){const crown=new THREE.Mesh(new THREE.ConeGeometry(1.65-j*.15,2.6,7),leaf);crown.position.y=3+j*.72;t.add(crown)}scene.add(t);scenery.push({o:t,span:396})}
for(let i=0;i<16;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(17+(i%4)*6,29+(i%5)*7,4),mat(0x829ca6));m.position.set((i-8)*39,-4,-210-(i%3)*20);m.rotation.y=.8;scene.add(m)}
const glass=mat(0x193b51,.1,.18),rubber=mat(0x191a1c,0,.98),rim=mat(0xc0c6cc,.85,.2),lamp=mat(0xfff0c8),tail=mat(0xd92121);
function fallbackCar(color,truck=false){const g=new THREE.Group(),paint=mat(color,.6,.25),len=truck?7.5:4.65;box(g,truck?2.45:2.12,.7,len,paint,0,.82,0);if(truck){box(g,2.4,2.35,4.1,mat(0xd6d6d6),0,2,1.5);box(g,2.3,1.3,1.85,paint,0,1.5,-2.7);box(g,2.12,.72,.07,glass,0,1.85,-3.66)}else{box(g,1.84,.72,2.08,glass,0,1.4,.12);box(g,1.76,.12,1.15,paint,0,1.79,.3);box(g,1.85,.1,.4,paint,0,1.3,2.05)}for(const z of(truck?[-2.8,1.2,2.75]:[-1.4,1.4]))for(const s of [-1,1]){for(const [radius,material,width] of [[truck?.51:.45,rubber,.34],[.23,rim,.36]]){const w=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,width,14),material);w.rotation.z=Math.PI/2;w.position.set(s*(truck?1.32:1.14),.46,z);g.add(w)}}for(const s of [-1,1]){box(g,.46,.16,.08,lamp,s*.74,.91,-len/2);box(g,.5,.16,.08,tail,s*.74,.91,len/2)}g.userData.length=len;return g}
const catalog=[{name:'Real GLB',color:0x2085db,price:0},{name:'Redline',color:0xe52b32,price:100},{name:'Golden',color:0xe9b92a,price:250},{name:'Night',color:0x25282d,price:500},{name:'Violet',color:0x8748cd,price:800},{name:'Emerald',color:0x188e64,price:1200}];
function read(k,d){try{const v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch{return d}}function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
let best=read('hr_best',0),wallet=read('hr_wallet',0),owned=read('hr_owned',[0]),selected=read('hr_selected',0);if(!Array.isArray(owned))owned=[0];if(!owned.includes(0))owned.push(0);if(!owned.includes(selected)||!catalog[selected])selected=0;
let player=fallbackCar(catalog[selected].color);player.position.set(0,.1,7);scene.add(player);let realCar=null;
function installPlayer(model){const old=player;model.position.copy(old.position);model.rotation.copy(old.rotation);model.userData.length=4.65;scene.remove(old);scene.add(model);player=model}
async function loadGLB(){try{const gltf=await new GLTFLoader().loadAsync('./models/car.glb');const root=gltf.scene;root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3());if(Math.min(s.x,s.y,s.z)<=0)throw Error('Model o‘lchami noto‘g‘ri');const scale=4.65/Math.max(s.x,s.z);root.scale.multiplyScalar(scale);root.rotation.y=Math.PI;root.updateMatrixWorld(true);const b2=new THREE.Box3().setFromObject(root),center=b2.getCenter(new THREE.Vector3());root.position.set(-center.x,-b2.min.y,-center.z);const wrap=new THREE.Group();wrap.add(root);wrap.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});realCar=wrap;if(selected===0)installPlayer(wrap);$('loadText').textContent='Haqiqiy avtomobil yuklandi!'}catch(e){console.warn('GLB yuklanmadi, zaxira avtomobil:',e);$('loadText').textContent='Zaxira avtomobil bilan boshlanmoqda'}finally{hide('loading')}}
loadGLB();
function selectCar(i){if(i===0&&realCar){installPlayer(realCar)}else{const c=fallbackCar(catalog[i].color);installPlayer(c)}selected=i;save('hr_selected',i)}
function updateMenu(){$('best').textContent=best;$('wallet').textContent=wallet;$('garageWallet').textContent=wallet}
function garage(){$('carList').replaceChildren();catalog.forEach((c,i)=>{const el=document.createElement('div');el.className='carCard'+(selected===i?' selected':'');const sw=document.createElement('div');sw.className='swatch';sw.style.background='#'+c.color.toString(16).padStart(6,'0');const name=document.createElement('h3');name.textContent=c.name;const price=document.createElement('p');price.textContent=owned.includes(i)?'Sotib olingan':c.price+' 🪙';const btn=document.createElement('button');btn.textContent=selected===i?'TANLANGAN':owned.includes(i)?'TANLASH':'SOTIB OLISH';btn.disabled=selected===i;btn.onclick=()=>{if(!owned.includes(i)){if(wallet<c.price){alert('Tangalar yetarli emas!');return}wallet-=c.price;owned.push(i);save('hr_wallet',wallet);save('hr_owned',owned)}selectCar(i);updateMenu();garage()};el.append(sw,name,price,btn);$('carList').append(el)})}
const lanes=[-5.6,0,5.6],traffic=[],coins=[];let state='menu',speed=0,distance=0,earned=0,spawnTime=0,coinTime=0,cameraMode=0;
function spawnTraffic(){const x=lanes[Math.random()*3|0];if(traffic.some(t=>Math.abs(t.o.position.x-x)<1&&t.o.position.z< -110))return;const truck=Math.random()<.22;const colors=[0xc83236,0xe0ddd4,0x292d36,0x248577,0xb4a16b];const o=fallbackCar(colors[Math.random()*colors.length|0],truck);o.position.set(x,.1,-165);scene.add(o);traffic.push({o,speed:30+Math.random()*45})}
const gold=new THREE.MeshStandardMaterial({color:0xffcf36,metalness:.8,roughness:.22,emissive:0x4d3200});function spawnCoin(){const o=new THREE.Mesh(new THREE.TorusGeometry(.57,.17,9,16),gold);o.position.set(lanes[Math.random()*3|0],1.35,-145);scene.add(o);coins.push(o)}
const keys={left:false,right:false,gas:false,brake:false};for(const k of Object.keys(keys)){const b=$(k);b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true;b.classList.add('pressed');b.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{keys[k]=false;b.classList.remove('pressed')})}const keyMap={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'gas',ArrowDown:'brake',a:'left',d:'right',w:'gas',s:'brake'};for(const [ev,val]of [['keydown',true],['keyup',false]])window.addEventListener(ev,e=>{const k=keyMap[e.key];if(k){e.preventDefault();keys[k]=val}});
function start(){traffic.forEach(t=>scene.remove(t.o));traffic.length=0;coins.forEach(c=>scene.remove(c));coins.length=0;speed=65;distance=earned=spawnTime=coinTime=0;player.position.set(0,.1,7);player.rotation.set(0,0,0);Object.keys(keys).forEach(k=>keys[k]=false);['menu','garage','pause','over'].forEach(hide);state='playing'}
function menu(){state='menu';['garage','pause','over'].forEach(hide);show('menu');updateMenu()}function pause(){if(state==='playing'){state='paused';show('pause')}}function end(){if(state!=='playing')return;state='over';best=Math.max(best,Math.floor(distance));wallet+=earned;save('hr_best',best);save('hr_wallet',wallet);$('finalDistance').textContent=Math.floor(distance);$('finalCoins').textContent=earned;show('over')}
$('start').onclick=start;$('restart').onclick=start;$('overMenu').onclick=menu;$('quit').onclick=menu;$('pauseBtn').onclick=pause;$('resume').onclick=()=>{hide('pause');state='playing'};$('garageBtn').onclick=()=>{hide('menu');garage();show('garage')};$('backGarage').onclick=()=>{hide('garage');show('menu')};$('cameraBtn').onclick=()=>cameraMode=(cameraMode+1)%3;
async function full(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape')}catch(e){console.info(e.message)}}$('fullBtn').onclick=full;$('rotateFull').onclick=full;
let quality=read('hr_quality',0);if(![0,1,2].includes(quality))quality=0;function applyQuality(){const q=['AUTO','LOW','HIGH'][quality];renderer.setPixelRatio(Math.min(devicePixelRatio,quality===2?1.6:quality===1?1:1.25));renderer.shadowMap.enabled=quality===2;sun.castShadow=quality===2;$('qualityBtn').textContent='GRAFIKA: '+q;save('hr_quality',quality)}$('qualityBtn').onclick=()=>{quality=(quality+1)%3;applyQuality()};sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;applyQuality();
function update(dt){speed+=((keys.gas?68:-13)-(keys.brake?135:0))*dt;speed=THREE.MathUtils.clamp(speed,0,230);const steer=(keys.right?1:0)-(keys.left?1:0);player.position.x=THREE.MathUtils.clamp(player.position.x+steer*(4.4+speed*.025)*dt,-6.95,6.95);player.rotation.z=THREE.MathUtils.damp(player.rotation.z,-steer*.055,7,dt);player.rotation.y=THREE.MathUtils.damp(player.rotation.y,-steer*.04,6,dt);const move=speed/3.6*dt;distance+=move;for(const s of scenery){s.o.position.z+=move;if(s.o.position.z>35)s.o.position.z-=s.span}spawnTime+=dt;coinTime+=dt;if(spawnTime>Math.max(1.05,2.15-distance/6000)){spawnTime=0;spawnTraffic()}if(coinTime>3.2){coinTime=0;spawnCoin()}for(let i=traffic.length-1;i>=0;i--){const t=traffic[i],o=t.o;o.position.z+=(speed-t.speed)/3.6*dt;if(Math.abs(o.position.x-player.position.x)<2&&Math.abs(o.position.z-player.position.z)<(o.userData.length+4.65)*.46){end();return}if(o.position.z>35||o.position.z< -210){scene.remove(o);traffic.splice(i,1)}}for(let i=coins.length-1;i>=0;i--){const c=coins[i];c.position.z+=move;c.rotation.y+=dt*4;if(Math.abs(c.position.x-player.position.x)<1.6&&Math.abs(c.position.z-player.position.z)<2.1){earned+=10;scene.remove(c);coins.splice(i,1)}else if(c.position.z>35){scene.remove(c);coins.splice(i,1)}}$('speed').textContent=Math.round(speed);$('distance').textContent=Math.floor(distance);$('coins').textContent=earned}
function updateCamera(dt){const target=cameraMode===0?[player.position.x*.62,5.6+speed*.008,17.4+speed*.012]:cameraMode===1?[player.position.x,2.5,5.5]:[player.position.x,1.65,6.8];camera.position.x=THREE.MathUtils.damp(camera.position.x,target[0],3.5,dt);camera.position.y=THREE.MathUtils.damp(camera.position.y,target[1],3,dt);camera.position.z=THREE.MathUtils.damp(camera.position.z,target[2],3,dt);camera.lookAt(player.position.x*.5,cameraMode===0?1.1:1.5,-16)}
window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);pause()});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});updateMenu();camera.position.set(0,6,19);const clock=new THREE.Clock();function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(state==='playing')update(dt);updateCamera(dt);renderer.render(scene,camera)}frame();
