import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id), show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x92c9ed);scene.fog=new THREE.Fog(0x92c9ed,65,230);
const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.1,450);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('game').append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe9f7ff,0x65744c,2.5));const sun=new THREE.DirectionalLight(0xffedcd,2.4);sun.position.set(-45,75,-60);scene.add(sun);
const mat=(c,r=0.75,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});const asphalt=mat(0x414447),pavement=mat(0x969a9b),white=mat(0xf3eee0),yellow=mat(0xf2cc55),green=mat(0x4c8b4d),brown=mat(0x79563d),glass=mat(0x183b53,.22,.25),tire=mat(0x15171a),silver=mat(0xabb8c4,.35,.65);
function box(p,w,h,d,m,x=0,y=0,z=0){let a=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);a.position.set(x,y,z);p.add(a);return a}
// Road: player drives toward negative Z. Environment scrolls toward positive Z.
box(scene,150,.1,460,green,0,-.18,-100);box(scene,21,.1,460,asphalt,0,0,-100);
for(let x of [-10.5,10.5]){box(scene,3,.15,460,pavement,x*1.14,.02,-100);box(scene,.22,.07,460,yellow,x,.12,-100)}
const scroll=[];for(let z=-210;z<32;z+=12){for(let x of [-3.5,3.5]){let a=box(scene,.17,.03,5,white,x,.11,z);scroll.push({o:a,span:252})}}
// Repeating urban scenery.
const facades=[mat(0xb98b6e),mat(0xb8b6aa),mat(0x8c9ca7),mat(0xd2aa8b),mat(0x8d817d)];const windowMat=mat(0x294757,.2,.4);
function building(x,z,n){let g=new THREE.Group();let h=8+(n%5)*5,w=7+(n%3)*2;box(g,w,h,9,facades[n%facades.length],0,h/2,0);for(let y=2;y<h-1;y+=3.4){for(let a=-w/2+1.1;a<w/2-.2;a+=2.1){box(g,1.05,1.6,.07,windowMat,a,y,4.54)}}g.position.set(x,0,z);scene.add(g);scroll.push({o:g,span:360})}
function tree(x,z,n){let g=new THREE.Group();box(g,.42,3,.42,brown,0,1.5,0);let crown=new THREE.Mesh(new THREE.SphereGeometry(1.7,7,5),green);crown.position.y=4;g.add(crown);g.position.set(x,0,z);scene.add(g);scroll.push({o:g,span:360})}
for(let i=0;i<30;i++){let z=-i*12;building(-21-(i%3)*2,z,i);building(21+(i%3)*2,z-5,i+2);tree(-14,z-3,i);tree(14,z-7,i)}
for(let x of [-10.8,10.8]){for(let z=-200;z<30;z+=18){let p=new THREE.Group();box(p,.14,7,.14,silver,0,3.5,0);box(p,1,.14,.14,silver,x<0?.5:-.5,6.9,0);box(p,.5,.18,.35,white,x<0?1:-1,6.85,0);p.position.set(x,0,z);scene.add(p);scroll.push({o:p,span:252})}}
// Detailed procedural fallback and AI traffic cars.
function simpleCar(color=0x257dc4,truck=false){let g=new THREE.Group(),paint=mat(color,.32,.6),length=truck?7:4.6;box(g,2.15,.72,length,paint,0,.78,0);if(truck){box(g,2.2,2.25,3.4,mat(0xcbd3d8),0,1.9,1.45);box(g,2.05,1.35,1.8,paint,0,1.55,-2.55);box(g,1.85,.7,.05,glass,0,1.7,-3.48)}else{box(g,1.8,.65,2.05,glass,0,1.35,-.05);box(g,1.75,.12,1.4,paint,0,1.75,-.1);box(g,1.9,.13,.3,paint,0,1.2,2.08)}for(let z of truck?[-2.45,1.1,2.6]:[-1.45,1.45])for(let x of [-1.16,1.16]){let wheel=new THREE.Mesh(new THREE.CylinderGeometry(.44,.44,.29,12),tire);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.46,z);g.add(wheel)}for(let x of [-.75,.75]){box(g,.42,.16,.07,mat(0xf8f3ce),x,.9,-length/2);box(g,.42,.17,.07,mat(0xd52c28),x,.9,length/2)}g.userData.length=length;return g}
let player=simpleCar(0x207ac9);player.position.set(0,.1,8);scene.add(player);let realModel=false;
// Actual supplied car.glb: centered and normalized. Exterior model is used for rear/hood views.
new GLTFLoader().load('./models/car.glb',gltf=>{let root=gltf.scene;root.rotation.y=Math.PI;root.updateMatrixWorld(true);let bounds=new THREE.Box3().setFromObject(root),size=bounds.getSize(new THREE.Vector3());let s=4.6/Math.max(size.x,size.z,.001);root.scale.setScalar(s);root.updateMatrixWorld(true);bounds.setFromObject(root);let c=bounds.getCenter(new THREE.Vector3());root.position.set(-c.x,-bounds.min.y,-c.z);root.traverse(o=>{if(o.isMesh){o.castShadow=false;o.frustumCulled=false}});let wrapper=new THREE.Group();wrapper.add(root);wrapper.position.copy(player.position);scene.remove(player);player=wrapper;player.userData.length=4.6;scene.add(player);realModel=true;$('status').textContent='GLB mashina tayyor ✓';},undefined,e=>{$('status').textContent='GLB topilmadi: zaxira mashina ishlaydi';console.warn(e)});
let mode='menu',speed=0,distance=0,coins=Number(localStorage.getItem('cityCoins')||0),traffic=[],elapsed=0,spawn=0,cameraMode=0,quality=0;const lanes=[-7,0,7],keys={left:false,right:false,gas:false,brake:false};$('coins').textContent=coins;
function newTraffic(){let x=lanes[Math.floor(Math.random()*3)],truck=Math.random()<.18,c=simpleCar([0xc03939,0xc7c8cc,0x233d55,0xd9bc65,0x559079][Math.floor(Math.random()*5)],truck);c.position.set(x,.1,-175);scene.add(c);traffic.push({o:c,v:truck?48:60+Math.random()*25})}
function reset(){traffic.forEach(t=>scene.remove(t.o));traffic=[];speed=0;distance=0;spawn=0;player.position.set(0,.1,8);mode='play';hide('menu');hide('paused');hide('crash')}
$('start').onclick=reset;$('again').onclick=reset;$('home').onclick=$('crashHome').onclick=()=>{mode='menu';hide('paused');hide('crash');show('menu')};$('pause').onclick=()=>{if(mode==='play'){mode='pause';show('paused')}};$('resume').onclick=()=>{mode='play';hide('paused')};$('reset').onclick=reset;$('camera').onclick=()=>{cameraMode=(cameraMode+1)%3;$('cockpit').classList.toggle('off',cameraMode!==2)};$('quality').onclick=()=>{quality=(quality+1)%3;let q=['AUTO','LOW','HIGH'][quality];renderer.setPixelRatio(Math.min(devicePixelRatio,[1.25,0.8,1.65][quality]));$('quality').textContent=q};
for(let key of Object.keys(keys)){let el=$(key);const set=(value)=>{keys[key]=value;el.classList.toggle('held',value)};el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);set(true)});for(let evt of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(evt,()=>set(false))}const keymap={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'gas',ArrowDown:'brake',a:'left',d:'right',w:'gas',s:'brake'};addEventListener('keydown',e=>{if(keymap[e.key]){e.preventDefault();keys[keymap[e.key]]=true}});addEventListener('keyup',e=>{if(keymap[e.key])keys[keymap[e.key]]=false});addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);if(mode==='play'){mode='pause';show('paused')}});
function update(dt){speed=THREE.MathUtils.clamp(speed+(keys.gas?65:-16)*dt-(keys.brake?120:0)*dt,0,190);let steer=(keys.right?1:0)-(keys.left?1:0);player.position.x=THREE.MathUtils.clamp(player.position.x+steer*(3+speed*.027)*dt,-8.1,8.1);player.rotation.z=THREE.MathUtils.damp(player.rotation.z,-steer*.045,6,dt);$('wheel').style.setProperty('--wheel',`${steer*38}deg`);let move=speed/3.6*dt;distance+=move;for(let s of scroll){s.o.position.z+=move;if(s.o.position.z>36)s.o.position.z-=s.span}spawn+=dt;if(spawn>Math.max(1.15,2.7-speed/150)){spawn=0;newTraffic()}for(let i=traffic.length-1;i>=0;i--){let t=traffic[i];t.o.position.z+=(speed-t.v)/3.6*dt;if(Math.abs(t.o.position.z-player.position.z)<(t.o.userData.length+4.6)*.42&&Math.abs(t.o.position.x-player.position.x)<2.2){mode='crash';$('result').textContent=`Masofa: ${(distance/1000).toFixed(2)} km`;show('crash')}if(t.o.position.z>35||t.o.position.z< -220){scene.remove(t.o);traffic.splice(i,1)}}if(cameraMode===0){camera.position.lerp(new THREE.Vector3(player.position.x*.6,5.4,17.6),Math.min(1,dt*4));camera.lookAt(player.position.x*.5,1.3,-18)}else if(cameraMode===1){camera.position.lerp(new THREE.Vector3(player.position.x,2.15,5.8),Math.min(1,dt*6));camera.lookAt(player.position.x,1.8,-28)}else{camera.position.lerp(new THREE.Vector3(player.position.x,2.25,7.4),Math.min(1,dt*6));camera.lookAt(player.position.x,2,-28)}player.visible=cameraMode===0;$('speed').textContent=$('dashSpeed').textContent=Math.round(speed);$('dist').textContent=(distance/1000).toFixed(2)+' KM';let newCoins=Math.floor(distance/120);if(newCoins>elapsed){coins+=newCoins-elapsed;elapsed=newCoins;localStorage.setItem('cityCoins',coins);$('coins').textContent=coins}}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.05);if(mode==='play')update(dt);renderer.render(scene,camera)}camera.position.set(0,5,18);camera.lookAt(0,1,-20);animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
